import { ArrowUpRight, Check } from "lucide-react";
import { Link } from "react-router-dom";
import PageIntro from "@/components/site/PageIntro";
import CtaBand from "@/components/site/CtaBand";
import { images } from "@/lib/site";

export default function About() {
  return <div data-testid="about-page"><PageIntro number="04" eyebrow="A grounded approach" title={<>Built for the<br /><span className="text-amber-300">road ahead.</span></>} description="ALS Royal Enfield Service is a local motorcycle workshop focused on practical care, repair conversations and keeping bikes road-ready." image={images.motorcycleSide} /><section className="section-shell" data-testid="about-story-section"><div className="grid gap-14 md:grid-cols-[0.85fr_1.15fr]"><div><p className="eyebrow">Care / clarity / consistency</p><h2 className="section-heading mt-5">Motorcycle care<br /><span className="text-white/40">without the noise.</span></h2></div><div><p className="body-copy">A good workshop experience should make it easier to understand what your motorcycle needs. At ALS, the starting point is simple: bring in the bike, explain the requirement, and build the work around that conversation.</p><p className="body-copy mt-6">The approach is service-focused and grounded in the realities of everyday riding — maintenance, repair, inspection and the small details that matter when you depend on your bike.</p><div className="mt-9 grid gap-3 sm:grid-cols-2">{["Practical service conversations", "Focused motorcycle attention", "Clear next steps", "Local workshop convenience"].map((value, index) => <div className="about-point" key={value} data-testid={`about-point-${index + 1}`}><Check size={15} className="text-amber-300" />{value}</div>)}</div></div></div></section><section className="image-statement-section" data-testid="about-image-section"><img src={images.motorcycleRear} alt="Motorcycle receiving workshop attention" data-testid="about-motorcycle-image" /><div className="image-statement-overlay"><p className="eyebrow">Road-ready starts here</p><h2 className="mt-4 font-display text-4xl font-black uppercase leading-[0.9] tracking-[-0.05em] text-white sm:text-6xl">The bike comes first.</h2></div></section><section className="section-shell" data-testid="about-visit-section"><div className="flex flex-col justify-between gap-8 border-t border-white/10 pt-8 sm:flex-row sm:items-end"><div><p className="eyebrow">No invented credentials. Just a clear offer.</p><h2 className="mt-4 max-w-2xl font-display text-3xl font-black uppercase leading-none tracking-[-0.04em] text-white sm:text-5xl">Service, repair and a place to start.</h2></div><Link to="/contact" className="text-link inline-flex" data-testid="about-contact-link">Talk to us <ArrowUpRight size={15} /></Link></div></section><CtaBand /></div>;
}
