import { ArrowUpRight, Clock3, MapPin, Phone } from "lucide-react";
import { Link } from "react-router-dom";
import { buttonVariants } from "@/components/ui/button";
import PageIntro from "@/components/site/PageIntro";
import { business, images } from "@/lib/site";

export default function Visit() {
  return <div data-testid="visit-page"><PageIntro number="06" eyebrow="Find the workshop" title={<>Make the<br /><span className="text-amber-300">visit.</span></>} description="ALS Royal Enfield Service is at Post Office Joka, 172, Mahatma Gandhi Road, Thakurpukur, Kolkata." image={images.storefront} /><section className="section-shell" data-testid="visit-details-section"><div className="visit-grid"><div className="visit-map-card"><img src={images.storefront} alt="ALS Royal Enfield Service storefront" data-testid="visit-storefront-image" /><div className="visit-map-overlay"><span className="eyebrow">ALS / Kolkata</span><strong>Thakurpukur</strong><small>West Bengal 700104</small></div></div><div className="visit-details"><p className="eyebrow">Workshop address</p><h2 className="mt-5 font-display text-3xl font-black uppercase leading-none tracking-[-0.04em] text-white" data-testid="visit-business-name">ALS Royal Enfield Service</h2><address className="mt-6 not-italic text-base leading-8 text-white/65" data-testid="visit-address">{business.address.map((line) => <span key={line} className="block">{line}</span>)}</address><a href={business.mapsUrl} target="_blank" rel="noreferrer" className={buttonVariants({ size: "lg", className: "cta-amber mt-8" })} data-testid="visit-directions-link"><MapPin size={16} /> Get directions <ArrowUpRight size={16} /></a><div className="mt-12 border-t border-white/10 pt-7"><div className="flex gap-4"><Clock3 className="mt-1 text-amber-300" size={19} /><div><p className="eyebrow">Service hours</p><p className="mt-3 text-sm leading-7 text-white/65"><strong className="block text-white">{business.hours.weekdays}</strong>{business.hours.weekdayTime}<strong className="mt-3 block text-white">{business.hours.sunday}</strong>{business.hours.sundayTime}</p></div></div></div><div className="mt-7 flex flex-col gap-3 sm:flex-row"><a href={`tel:${business.phones[0]}`} className={buttonVariants({ variant: "outline", size: "lg", className: "cta-outline" })} data-testid="visit-call-link"><Phone size={16} /> Call now</a><Link to="/book" className={buttonVariants({ variant: "outline", size: "lg", className: "cta-outline" })} data-testid="visit-book-link">Book a service <ArrowUpRight size={16} /></Link></div></div></div></section><section className="dark-section" data-testid="visit-note-section"><div className="mx-auto max-w-[1440px] px-5 py-16 sm:px-8 lg:px-12 lg:py-24"><p className="eyebrow">Before you arrive</p><h2 className="mt-5 max-w-2xl font-display text-4xl font-black uppercase leading-[0.92] tracking-[-0.05em] text-white sm:text-6xl">Call, enquire or<br /><span className="text-amber-300">just find us.</span></h2><p className="mt-6 max-w-lg text-base leading-7 text-white/55">For a service conversation, call ahead or use the enquiry form to share what your bike needs. We do not confirm appointments online in this demo.</p></div></section></div>;
}
